### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원가입 테스트
POST http://localhost:8001/api/v1/members/signup
Content-Type: application/json

{
  "memberId": "testId2",
  "memberPassword": "pass02",
  "memberName": "새로운 이름22",
  "memberEmail": "aaa@aaa.com"
}

### 로그인 테스트
POST http://localhost:8001/api/v1/members/login
content-Type: application/json

{
  "memberId" : "testId2",
  "memberPassword": "pass02"
}